src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProductRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 250, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 50)]
    private ?string $sku = null;

    #[ORM\Column(length: 250)]
    #[Assert\NotBlank]
    private ?string $product_name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    private ?\DateTimeInterface $created_at = null;

    private ?\DateTimeInterface $updated_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSku(): ?string
    {
        return $this->sku;
    }

    public function setSku(?string $sku): static
    {
        $this->sku = $sku;

        return $this;
    }

    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    public function setProductName(?string $product_name): static
    {
        $this->product_name = $product_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductFormType;
use App\Repository\ProductRepository;
use App\Request\StoreProductsRequest;
use App\Request\UpdateProductsRequest;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/api', name: 'api_')]
class ProductController extends AbstractController
{
    private $productRepository;
    private $em;

    public function __construct(ProductRepository $productRepository, EntityManagerInterface $em)
    {
        $this->productRepository = $productRepository;
        $this->em = $em;
    }

    #[Route('/products', name: 'get_all_products', methods:['GET'])]
    public function getAll(Request $request): Response
    {
        $products = $this->productRepository->findAll();
        return $this->render('product/index.html.twig', [
            'products' => $products,
        ]);
    }

    #[Route('/products/getById/{id}', name: 'get_product_by_id', methods:['GET'])]
    public function getById(Request $request): Response
    {
        $product = $this->productRepository->find($request->get('id'));
        $serializer = new Serializer([new ObjectNormalizer()]);
        $data = $serializer->normalize($product, null, [AbstractNormalizer::ATTRIBUTES => ['id', 'name', 'sku']]);
        
        return new JsonResponse(['status' => 'sucess', 'data' => $data], 200);
    }

    #[Route('/product/single/store', name: 'store_product')]
    public function store(Request $request): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductFormType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $new_product = $form->getData();
            $this->em->persist($new_product);
            $this->em->flush();
            return $this->redirect('/api/products');
        } else {
            return $this->render('product/create.html.twig', [
                'form' => $form->createView(),
                'error' => ''
            ]);
        }
    }

    #[Route('/products/store', name: 'store_product', methods: ['POST'])]
    public function storeBulk(StoreProductsRequest $request): Response
    {
        $products = $this->productRepository->storeBulk($request->getRequest()->toArray()['products']);

        return new JsonResponse($products);
    }

    #[Route('/products/delete', name: 'delete_product', methods:['DELETE'])]
    public function delete(Request $request): Response
    {
        return $this->render('product/index.html.twig', [
            'controller_name' => 'ProductController',
        ]);
    }

    #[Route('/products/update', name: 'update_product', methods:['PUT'])]
    public function update(UpdateProductsRequest $request): Response
    {
        $products = $this->productRepository->updateBulk($request->getRequest()->toArray()['products']);

        return new JsonResponse($products);
    }
}

templates/product/create.html.twig
{% extends "./dashboard.html.twig" %}

{% block body %}
<div class="w-4/5 m-auto pt-40">
    <h1 class="text-6xl text-center pb-12">
        Create Product
    </h1>
    {% if error %} 
        <div>
            <h3>{{error}}<h3>
        </div>
    {% endif %}
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button    
            type="submit"
            class="uppercase mt-15 bg-blue-500 text-gray-100 text-lg font-extrabold py-4 px-8 rounded-3xl">
            Submit Product
        </button>

    {{ form_end(form) }}
</div>
{% endblock %}

templates/product/edit.html.twig
{% extends "./dashboard.html.twig" %}

{% block body %}
<div class="w-4/5 m-auto pt-40">
    <h1 class="text-6xl text-center pb-12">
        Create Movie
    </h1>

    {{ form_start(form) }}

        {{ form_widget(form) }}
        
        <button    
            type="submit"
            class="uppercase mt-15 bg-blue-500 text-gray-100 text-lg font-extrabold py-4 px-8 rounded-3xl">
            Submit Product
        </button>

    {{ form_end(form) }}
</div>
{% endblock %}

templates/product/index.html.twig
{% extends "./dashboard.html.twig" %}

{% block body %}
    <div class="flex flex-row">
        {% for product in products %}
            <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 m-4">
                    <img class="rounded-t-lg" src="https://placehold.co/250x200/png" alt="" />
                <div class="p-5">
                    <a href="#">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ product.productName }}</h5>
                    </a>
                    <a href="/api/products/getById/{{ product.id }}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        More Information
                        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                        </svg>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/product/show.html.twig
{% extends "./dashboard.html.twig" %}

{% block body %}
    {% if product %}
        <div class="sm:w-3/5 w-4/5 mx-auto">
            <h1 class="pt-20 sm:text-5xl md:text-7xl text-4xl font-bold text-center">
                {{ product.productName }}
            </h1>
            <p class="text-xl py-6">
                {{ product.description }}
            </p>
        </div>
    {% else %}
        <div>
            <h1> The product is out of stock </h1>
        </div>
    {% endif %}
{% endblock %}